//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok_uygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Stok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Stok()
        {
            this.tbl_StokHareket = new HashSet<tbl_StokHareket>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string kod { get; set; }
        public string aciklama { get; set; }
        public Nullable<int> adet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_StokHareket> tbl_StokHareket { get; set; }
    }
}
