//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stok_uygulaması.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StokHareket
    {
        public int id { get; set; }
        public Nullable<int> stokID { get; set; }
        public Nullable<int> alinanAdet { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual tbl_Stok tbl_Stok { get; set; }
    }
}
